### ISSUE TITLE
worker.on is not a function

### ISSUE THREAD

**Issue by viperfx** [jbielick/faktory_worker_node#157] opened 2021-06-16 12:30 UTC
node.js version:
14
npm/yarn version:
1.22.5
faktory-server version: 
Faktory 1.5.1
`facktory-worker` package version:
4.1.4
#### Code sample:

```js
import { db } from '../api/src/lib/db'
import { logger } from '../api/src/lib/logger'

const faktory = require('faktory-worker')

faktory.register('ResizeImage', async ({ id, size }) => {
  console.log('run ResizeImage')
})

export default async ({ args }) => {
  const worker = await faktory.work()
  worker.on('fail', ({ job, error }) => {
    logger.debug({ job, error }, `Faktory worker failure event`)
  })
}

```

#### Expected Behavior:

No error should be produced

#### Actual Behavior:

Error causes the worker to crash with `worker.on is not a function`

#### Steps to reproduce the behavior or a test case:

Use the script provided above.

**Comment by jbielick** [comment] 2021-06-17 12:45
I'm using the script you provided, but I cannot reproduce this error. Are you `await`ing `faktory.work()` when you see this error? `.on` would not be a function if it were called on the promise returned by `faktory.work()`.

```js
const faktory = require(require.resolve("../../lib/faktory"));

faktory.register("ResizeImage", async ({ id, size }) => {
  console.log("run ResizeImage");
});

(async () => {
  const worker = await faktory.work();
  console.log(typeof worker.on);
  worker.on("fail", ({ job, error }) => {
    logger.debug({ job, error }, `Faktory worker failure event`);
  });
})();
```

And here's a test that passes: https://github.com/jbielick/faktory_worker_node/commit/bc9ba0fb2b73cb6e3528a113516164d33267ee77

```js
test('.work() resolves the worker after starting', async (t) => {
  const faktory = create();
  const worker = await faktory.work();

  worker.on('test', () => { });

  t.is(worker.listenerCount('test'), 1);
});
```

Is there a simplified example you can provide that fails?

**Comment by viperfx** [comment] 2021-06-18 22:59
Thanks for your reply and for trying to reproduce it. So I am currently trying to invoke faktory.work() inside a redwoodjs CLI script. 

The CLI script (I contributed to it), takes a node script path, imports it and awaits the default function inside it.

https://github.com/redwoodjs/redwood/blob/main/packages/cli/src/commands/exec.js#L12-L16

I have taken the nodejs code and put it into a normal node script, and the worker does run (and hang). But with the CLI through redwood, it starts up but eventually just exists. 

Here is an example output of what I see.

```
# DEBUG=faktory* yarn rw exec taskWorker
yarn run v1.22.5
[18:55:17] Generating Prisma client [started]
[18:55:17] Generating Prisma client [completed]
[18:55:17] Running script [started]
  faktory-worker registered ResizeImage +0ms
  faktory-worker:worker work concurrency=20 +0ms
  faktory-worker:client:heart BEAT +0ms
  faktory-worker:connection-pool +1 +0ms
  faktory-worker:connection connecting +0ms
  faktory-worker:client handshake +0ms
....
  faktory-worker:client handshake +84ms
  faktory-worker:connection SEND: HELLO {"hostname":"MacbookPro.local","v":2,"labels":[],"pid":25067,"wid":"c2795bdd"} +18ms
  faktory-worker:connection client='HELLO {"hostname":"MacbookPro.local","v":2,"labels":[],"pid":25067,"wid":"c2795bdd"}', server='OK' +13ms
  faktory-worker:connection SEND: FETCH default +1ms
  faktory-worker:worker starting p18 +97ms
  faktory-worker:connection-pool +1 +97ms
  faktory-worker:connection connecting +65ms
  faktory-worker:client handshake +102ms
  faktory-worker:connection SEND: HELLO {"hostname":"MacbookPro.local","v":2,"labels":[],"pid":25067,"wid":"c2795bdd"} +23ms
  faktory-worker:connection client='HELLO {"hostname":"MacbookPro.local","v":2,"labels":[],"pid":25067,"wid":"c2795bdd"}', server='OK' +5ms
  faktory-worker:connection SEND: FETCH default +0ms
  faktory-worker:worker starting p19 +101ms
  faktory-worker:connection-pool +1 +100ms
  faktory-worker:connection connecting +72ms
function
[18:55:22] Running script [completed]
✨  Done in 9.95s.
```

I imagine redwood is prob not something you used, or have experience with, but if you have any clues from looking at the implementation for exec.js in redwood and how we are running node scripts - that may prevent a library like faktory from working  - do let me know! 

I can also provide you a simple redwood app to reproduce the issue if it would help.

**Comment by viperfx** [comment] 2021-06-20 21:39
Here is a repo with a redwood app to reproduce the issue. Ive included steps in the README.

https://github.com/viperfx/redwood-faktory-worker

**Comment by viperfx** [comment] 2021-06-22 16:52
Hey @jbielick - did you have a chance to review the above messages or reproduce the issue from the repo I provided? Let me know if I can be of more help or provide further info for you.

**Comment by jbielick** [comment] 2021-06-22 17:20
@viperfx yeah. I think the repo is missing `faktory-worker` in package.json and `@redwoodjs/cli`, but after I installed those I got something working.

I believe the issue is that redwoodjs is exiting after awaiting your script:

https://github.com/redwoodjs/redwood/blob/06a702ad5d453808b295015a310c26016af1fe61/packages/cli/src/commands/exec.js#L87-L90 

The docs mention that `await faktory.work()` will block until the worker stops, but this is not true anymore. In other words, that comment / documentation is wrong. `faktory.work()` resolves after the worker starts up successfully. To avoid a memory leak, it does not hold a promise until shutdown.

Honestly I think calling `process.exit(0)` after calling a userland function is a bit strange, but I'm not a node expert. I don't know what you could do off the top of my head to make this work at the moment. If redwood did not `process.exit(0)` it would work fine as the process would stay running while there are either A.) open connections or B.) stuff on the event loop—both of which are true after `faktory.work()` resolves.

I'll update the docs.

**Comment by viperfx** [comment] 2021-06-22 17:37
Oh sorry about the missing packages! Glad you were able to reproduce. 

Thanks for looking into this and your suggestion to the issue - I will discuss a potential PR for redwood that could help resolve this.

**Comment by jbielick** [comment] 2021-06-22 17:51
👍🏻  closing as there isn't much to do and I've updated the docs.

**Closed by jbielick** 2021-06-22 17:51 UTC

**Comment by jbielick** [comment] 2021-06-23 14:35
I was trying to think of a workaround and has an idea. Apologies if redwood doesn't have something like this or if this won't work.

If you can run your own script without having to use the redwood CLI, you could probably run this just fine.

Instead of `yarn rw exec runWorker.js`, you could do something like the following (assuming there is something like redwood.boot you can use).

```js
require('redwood/boot') // <-- I made this up. Is there a way to boot your framework in a script?
const faktory = require('faktory-worker')

faktory.register(...)

faktory.work().catch('error', console.error.bind(console));
```

If there's some way you can boot redwood yourself and don't have to use `rw exec`, it would work fine by just running your own script: `node runWorker.js` for example.
